export const CHANGE_GRID_SIZE = 'CHANGE_GRID_SIZE';
export const CHANGE_GRID_ARRAY = 'CHANGE_GRID_ARRAY';
export const CHANGE_PLAYING_NOW = 'CHANGE_PLAYING_NOW';
export const CHANGE_GENERATIONS_COUNT = 'CHANGE_GENERATIONS_COUNT';
export const CHANGE_GAME_SPEED = 'CHANGE_GAME_SPEED';